### ISSUE TITLE
Show a nice report

### ISSUE THREAD

**Issue by cool-RR** [pberkes/big_O#30]
Having to type the following: 

```python
best, others = big_o.big_o(heapify, data_generator_heapify, max_n=10**7)
print(best)
print()
for other in others:
    print(other)
print()
```

Is quite a drag. Also there needs to be a clear separation between `best` and `others`

Would be nice if there was a `print_report` function that prints it all for you, with a clear indication of which solution is likely best. This library looks like it's mostly for diagnostic usage anyway.

**Comment by harisaisundhar** [comment]
Can I be assigned to this ?

**Comment by pberkes** [comment]
Sure! Would you mind suggesting what the report could look like before implementing? I think it would save some time rather than discuss after the fact

**Comment by harisaisundhar** [comment]
Sure! The best algo could just be printed as it is. As of the others, we could print a table which has rows [Ranking, Complexities, Time, Residuals] where the complexities are sorted on ascending based on their time.

**Comment by harisaisundhar** [comment]
Also since this print_report function can only be called for the results of big_o function, it would be better to create a this function within the big_o() function only with a new default parameter print_report. 

By default we could initialise it to False, thus it will not break any current code. Users who needs to get the report can send a parameter with print_report = True to get the reports printed. 

Just an idea, does that sound good to you. Or do you have any other ways to achieve this in mind ?

**Comment by pberkes** [comment]
I'm not fond of that idea, because it leads to an explosion of keyword arguments in the long run. The general principle is to separate calculations and reporting/plotting.

I think the idea would be to write something like 
```
best, others = big_o.big_o(heapify, data_generator_heapify, max_n=10**7)
print(big_o_report(best, others))
```
and big_o_report returns a nicely formatted string.

`big_o_report` could live in a new module `reports`

**Comment by pberkes** [comment]
Part of this task would also be to add the usage as an example in the documentaion

**Comment by harisaisundhar** [comment]
Got it! That can be done. Will start working on it. Can I go ahead with the proposed table design for report ?
